# Generated by Django 5.0.6 on 2024-06-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_maltrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechaVacuna', models.CharField(max_length=200)),
                ('tipoVacuna', models.CharField(max_length=200)),
                ('proximaVacuna', models.CharField(max_length=200)),
            ],
        ),
    ]
