# Generated by Django 5.0.6 on 2024-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_vacunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=200)),
                ('edad', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
