# Generated by Django 5.0.6 on 2024-06-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_registrar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('monto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
