# Generated by Django 5.0.6 on 2024-06-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='tasks.registrar'),
        ),
    ]
