# Generated by Django 5.0.6 on 2024-06-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_adopcion_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrar',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
    ]
